apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/wp7790/argo-gitops.git'
    targetRevision: HEAD
    path: argo-gitops/argo-gitops/apps/dev/sample-app/overlay/dev 
    kustomize:
      namePrefix: sample-
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
