apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: grade-demo
spec:
  type: NodePort
  selector:
    app: grade-submission
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
