apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.3.2  # pick a stable version
    helm:
      values: |
        service:
          type: ClusterIP
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
