apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wp7790/hello-api-deployments.git
    targetRevision: main
    path: apps/hello-api/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
